[tool.poetry]
name = "idid"
version = "0.1.0"
description = "iDID Flask Backend"
authors = ["Nigel <nigelchimwene@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
