services:
  - type: web
    name: idid-backend
    env: python
    buildCommand: cd backend && pip install poetry && poetry install
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11