services:
  - type: web
    name: idid-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11